language: ruby
rvm:
  - "2.0.0"
env:
  - DB=postresql
script: 
  - bundle exec rake db:test:prepare --trace
  - bundle exec rspec
before_script:
  - psql -c 'create database epicodus_overflow_test;' -U postgres